id: P003150
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:43:41.623019
source_metadata:
  id: bdr:W21609
  title: དབལ་མང་པཎྜི་ཏའི་རྣམ་ཐར
  author: ''
  volumes:
    b82a4978570b46a1bc4331dd6e02bad6:
      image_group_id: I4212
      title: ''
      volume_number: 1
      total_pages: 612
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
